name: Suggest
description: Propose suggestions for the script.
title: "[Suggest]: "
labels: ["建议"]
assignees:
  - dawn-lc
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before Making Suggestions...
      options:
      - label: I have searched existing suggestions and found no similar ones
        required: true
      - label: I have spent at least 5 minutes thinking and preparing before making this suggestion
        required: true
      - label: I am using the latest version of the script
        required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: scriptManager
    attributes:
      label: Which script manager are you using?
      options:
        - Tampermonkey
        - Tampermonkey Beta
        - ScriptCat
        - Violentmonkey
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What is the script version?
      placeholder: e.g., 3.1.1
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe Your Suggestion
      description: Briefly describe your suggestion
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: Detailed Description of the Suggestion
      description: |
        Any related information? Links? References?
        Anything that helps us understand your suggestion better.
    validations:
      required: false
