name: 提案する
description: スクリプトに対する提案を提出する
title: "[提案]: "
labels: ["建议"]
assignees:
  - dawn-lc
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 提案の前に...
      options:
        - label: 既存の提案を検索し、類似の提案が見つかりませんでした
          required: true
        - label: 提案をする前に少なくとも5分間、考えたり準備したりしました
          required: true
        - label: 短く明確なタイトルを記入し、開発者がIssueリストを閲覧する際に状況を素早く把握できるようにしました
          required: true
        - label: これらの内容を注意深く読んでおらず、これが後の処理に影響しないと信じています
          required: false
        - label: 最新版のスクリプトを使用しています
          required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 使用しているブラウザは何ですか？
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - その他
    validations:
      required: true
  - type: dropdown
    id: scriptManager
    attributes:
      label: 使用しているスクリプトマネージャーは何ですか？
      options:
        - Tampermonkey
        - Tampermonkey Beta
        - ScriptCat
        - Violentmonkey
        - その他
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: スクリプトのバージョンは何ですか？
      placeholder: 例 3.1.1
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 提案を説明してください
      description: 提案を簡潔に説明してください
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: 提案の具体的な説明
      description: |
        関連する情報？リンク？参考資料？
        提案をより理解するための情報を提供してください。
    validations:
      required: false
  - type: checkboxes
    id: finalCheck
    attributes:
      label: 最後のステップ...
      options:
        - label: 上記の内容を注意深く記入しておらず、これが後の処理に影響しないと信じています
          required: false
