name: Preview
on:
  push:
    branches: 
      - dev
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/*'
      - 'build/*'
      - 'utils/*'
      - '.github/workflows/Preview.yml'
env:
  release_tag: preview 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    permissions:
      contents: write
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build ${{ env.release_tag }}
    - name: 获取编译结果
      run: |
        FILES=$(find dist -type f | tr '\n' ' ')
        echo "file_list=${FILES}" >> $GITHUB_ENV
    - name: 获取版本号
      run: |
        PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
        echo "current_version=${PACKAGE_VERSION}" >> $GITHUB_ENV
    - name: 发布版本
      run: |
        gh release create v${{ env.current_version }} ${{ env.file_list }} \
          --target dev \
          --prerelease \
          --title "${{ env.current_version }}" \
          --notes "${{ env.current_version }} ${{ github.sha}}"
    - name: 删除旧版本
      run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
      continue-on-error: true
    - name: 发布预览版本
      run: |
        gh release create ${{ env.release_tag }} ${{ env.file_list }} \
          --target dev \
          --prerelease \
          --title "预览版/Release ${{ env.current_version }}" \
          --generate-notes